name: equatable_ddd_modeling
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-268.18.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^2.1.0
  # localization helper
  intl: ^0.17.0
  # localization automation
  intl_utils: ^2.4.0
  equatable: ^2.0.3
  dartz: ^0.10.1 
  uuid: ^3.0.5
  
 

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  # code metrics
  dart_code_metrics: ^4.5.0
  build_runner: ^2.1.7
  mocktail: ^0.2.0


  lint: ^1.8.2




  


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
# flutter intl for localization settings
flutter_intl:
  enabled: true   
  class_name: S   
  main_locale: en 
  arb_dir: lib/src/localization
  output_dir: lib/src/localization_gen
  use_deferred_loading: false

